# Generated by Django 4.2.30 on 2026-07-07 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_category_delete_category'),
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('brewery', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('abv', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garnish',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('made_in_house', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('made_in_house', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='liqueur',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('distillery', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('proof', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('detail_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.detailcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Mixer',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('made_in_house', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='spirit_detail', serialize=False, to='products.product')),
                ('distillery', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('proof', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('detail_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.detailcategory')),
                ('spirit_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.spiritcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('winery', models.CharField(blank=True, max_length=100, null=True)),
                ('varietal', models.CharField(blank=True, max_length=100, null=True)),
                ('vintage', models.CharField(blank=True, max_length=4, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='garnishdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ingredientdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='liqueurdetail',
            name='detail_category',
        ),
        migrations.RemoveField(
            model_name='liqueurdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mixerdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='spiritdetail',
            name='detail_category',
        ),
        migrations.RemoveField(
            model_name='spiritdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='spiritdetail',
            name='spirit_category',
        ),
        migrations.RemoveField(
            model_name='winedetail',
            name='name',
        ),
        migrations.DeleteModel(
            name='BeerDetail',
        ),
        migrations.DeleteModel(
            name='GarnishDetail',
        ),
        migrations.DeleteModel(
            name='IngredientDetail',
        ),
        migrations.DeleteModel(
            name='liqueurDetail',
        ),
        migrations.DeleteModel(
            name='MixerDetail',
        ),
        migrations.DeleteModel(
            name='SpiritDetail',
        ),
        migrations.DeleteModel(
            name='WineDetail',
        ),
    ]
