# Generated by Django 4.2.30 on 2026-07-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_beer_garnish_ingredient_liqueur_mixer_spirit_wine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liqueur',
            old_name='distillery',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='spirit',
            name='proof',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
