# Generated by Django 4.2.30 on 2026-08-10 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
        ('products', '0003_remove_product_category_delete_category'),
        ('bar', '0003_rename_distillery_liqueur_brand_alter_spirit_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('notes', models.TextField(blank=True, null=True)),
                ('garnish', models.ManyToManyField(blank=True, to='bar.garnish')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
    ]
