from django.urls import path
from bar import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('spirits/', views.SpiritListView.as_view(), name='spirit-list'),
    path('spirits/<int:pk>/', views.SpiritDetailView.as_view(), name='spirit-detail'),
    path('spirits/create/', views.SpiritCreateView.as_view(), name='spirit-create'),
    path('spirits/<int:pk>/update/', views.SpiritUpdateView.as_view(), name='spirit-update'),
    path('spirits/<int:pk>/delete/', views.SpiritDeleteView.as_view(), name='spirit-delete'),
    path('beers/', views.BeerListView.as_view(), name='beer-list'),
    path('beers/<int:pk>/', views.BeerDetailView.as_view(), name='beer-detail'),
    path('beers/create/', views.BeerCreateView.as_view(), name='beer-create'),
    path('beers/<int:pk>/update/', views.BeerUpdateView.as_view(), name='beer-update'),
    path('beers/<int:pk>/delete/', views.BeerDeleteView.as_view(), name='beer-delete'),
    path('wines/', views.WineListView.as_view(), name='wine-list'),
    path('wines/<int:pk>/', views.WineDetailView.as_view(), name='wine-detail'),
    path('wines/create/', views.WineCreateView.as_view(), name='wine-create'),
    path('wines/<int:pk>/update/', views.WineUpdateView.as_view(), name='wine-update'),
    path('wines/<int:pk>/delete/', views.WineDeleteView.as_view(), name='wine-delete'),
    path('liqueurs/', views.LiqueurListView.as_view(), name='liqueur-list'),
    path('liqueurs/<int:pk>/', views.LiqueurDetailView.as_view(), name='liqueur-detail'),
    path('liqueurs/create/', views.LiqueurCreateView.as_view(), name='liqueur-create'),
    path('liqueurs/<int:pk>/update/', views.LiqueurUpdateView.as_view(), name='liqueur-update'),
    path('liqueurs/<int:pk>/delete/', views.LiqueurDeleteView.as_view(), name='liqueur-delete'),
    path('mixers/', views.MixerListView.as_view(), name='mixer-list'),
    path('mixers/<int:pk>/', views.MixerDetailView.as_view(), name='mixer-detail'),
    path('mixers/create/', views.MixerCreateView.as_view(), name='mixer-create'),
    path('mixers/<int:pk>/update/', views.MixerUpdateView.as_view(), name='mixer-update'),
    path('mixers/<int:pk>/delete/', views.MixerDeleteView.as_view(), name='mixer-delete'),
    path('ingredients/', views.IngredientListView.as_view(), name='ingredient-list'),
    path('ingredients/<int:pk>/', views.IngredientDetailView.as_view(), name='ingredient-detail'),
    path('ingredients/create/', views.IngredientCreateView.as_view(), name='ingredient-create'),
    path('ingredients/<int:pk>/update/', views.IngredientUpdateView.as_view(), name='ingredient-update'),
    path('ingredients/<int:pk>/delete/', views.IngredientDeleteView.as_view(), name='ingredient-delete'),
    path('garnishes/', views.GarnishListView.as_view(), name='garnish-list'),
    path('garnishes/<int:pk>/', views.GarnishDetailView.as_view(), name='garnish-detail'),
    path('garnishes/create/', views.GarnishCreateView.as_view(), name='garnish-create'),
    path('garnishes/<int:pk>/update/', views.GarnishUpdateView.as_view(), name='garnish-update'),
    path('garnishes/<int:pk>/delete/', views.GarnishDeleteView.as_view(), name='garnish-delete')
]