# Generated by Django 4.2.30 on 2026-06-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='InventoryItem',
        ),
    ]
