# Generated by Django 4.2.30 on 2026-07-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributor',
            old_name='name',
            new_name='distributor_name',
        ),
        migrations.RenameField(
            model_name='inventorystock',
            old_name='product',
            new_name='stock_item',
        ),
        migrations.RenameField(
            model_name='stockitem',
            old_name='stock_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='product',
            new_name='stock_item',
        ),
    ]
