# Generated by Django 4.2.30 on 2026-06-30 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar_products', '0001_initial'),
        ('inventory', '0002_rename_product_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar_products.barproduct'),
        ),
    ]
