# Generated by Django 4.2.30 on 2026-06-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar_products', '0001_initial'),
        ('inventory', '0004_alter_distributor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.distributor'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar_products.barproduct'),
        ),
    ]
