# Generated by Django 4.2.30 on 2026-06-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventoryitem_distributor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='name',
            new_name='inventory_name',
        ),
    ]
