# Generated by Django 4.2.30 on 2026-07-01 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar_products', '0003_beerdetail_category_garnishdetail_ingredientdetail_and_more'),
        ('inventory', '0006_rename_name_inventoryitem_inventory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.distributor')),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar_products.barproduct')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='inventory_name',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='inventorystock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitem'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitem'),
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
