# Generated by Django 4.2.30 on 2026-07-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_order_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='price',
            new_name='unit_cost',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost_at_purchase',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10),
            preserve_default=False,
        ),
    ]
