# Generated by Django 4.2.30 on 2026-07-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_price_stockitem_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='par_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
