# Generated by Django 4.2.30 on 2026-07-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockitem_par_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit_cost_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
