# Generated by Django 4.2.30 on 2026-07-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stockitem_current_average_unit_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='last_purchashed_date',
            new_name='last_purchased_at',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
