# Generated by Django 4.2.30 on 2026-08-06 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_last_purchashed_date_stockitem_last_purchased_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='unit_cost',
        ),
    ]
