# Generated by Django 4.2.30 on 2026-08-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_stockitem_unit_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='order_processed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
