# Generated by Django 4.2.30 on 2026-08-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_orderitem_order_date_order_order_processed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_received',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
    ]
