# Generated by Django 4.2.30 on 2026-08-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_orderitem_quantity_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
