# Generated by Django 4.2.30 on 2026-08-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_orderitem_quantity_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='units',
            field=models.CharField(choices=[('ml', 'Milliliter'), ('l', 'Liter'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('cup', 'Cup'), ('pt', 'Pint'), ('qt', 'Quart'), ('gal', 'Gallon'), ('fl oz', 'Fluid Ounce'), ('g', 'Gram'), ('kg', 'Kilogram'), ('oz', 'Ounce'), ('lb', 'Pound')], max_length=50),
        ),
    ]
