# Generated by Django 4.2.30 on 2026-09-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_stockitem_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystock',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
