# Generated by Django 4.2.30 on 2026-08-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='units',
            field=models.CharField(choices=[('ml', 'Milliliter'), ('l', 'Liter'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('cup', 'Cup'), ('pt', 'Pint'), ('qt', 'Quart'), ('gal', 'Gallon'), ('fl oz', 'Fluid Ounce'), ('g', 'Gram'), ('kg', 'Kilogram'), ('oz', 'Ounce'), ('lb', 'Pound'), ('pc', 'Piece'), ('doz', 'Dozen'), ('pair', 'Pair'), ('dash', 'Dash'), ('pinch', 'Pinch'), ('sprinkle', 'Sprinkle'), ('cube', 'Cube')], max_length=50),
        ),
    ]
