# Generated by Django 4.2.30 on 2026-06-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barproduct',
            old_name='name',
            new_name='product_name',
        ),
    ]
