# Generated by Django 4.2.30 on 2026-07-01 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar_products', '0002_rename_name_barproduct_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerDetail',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bar_products.barproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GarnishDetail',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bar_products.barproduct')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientDetail',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bar_products.barproduct')),
            ],
        ),
        migrations.CreateModel(
            name='liqueurDetail',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bar_products.barproduct')),
            ],
        ),
        migrations.CreateModel(
            name='MixerDetail',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bar_products.barproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SpiritDetail',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bar_products.barproduct')),
            ],
        ),
        migrations.CreateModel(
            name='WineDetail',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bar_products.barproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='Beer',
        ),
        migrations.DeleteModel(
            name='Bitters',
        ),
        migrations.DeleteModel(
            name='liqueur',
        ),
        migrations.DeleteModel(
            name='Spirit',
        ),
        migrations.DeleteModel(
            name='Wine',
        ),
        migrations.AddField(
            model_name='barproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bar_products.category'),
        ),
    ]
