# Generated by Django 4.2.30 on 2026-07-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_products', '0004_detailcategory_spiritcategory_beerdetail_abv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spiritdetail',
            name='type',
        ),
        migrations.AddField(
            model_name='mixerdetail',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
